# Playbook to build images and coordinate containers on localhost using Docker

---
- hosts: localhost
  vars:
    basedir: "{{ lookup('env', 'PLAYBOOK_BASEDIR') }}"
    rebuild_existing_images: true

    # EYE reasoner
    eye:
      repo:
        path: "{{ basedir }}/eye"
      image:
        name: eye:latest
  tasks:
    # Build image for EYE reasoner
    - name: Build image for EYE reasoner
      community.docker.docker_image:
        source: "build"
        force_source: "{{ rebuild_existing_images }}"
        build:
          path: "{{ eye.repo.path }}"
        name: "{{ eye.image.name }}"
      tags:
        - build
        - eye
        - build-eye
